name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-20.04
    name: Debug CI
    steps:
    - name: test ls
      run: ls -l
    - name: Python version
      run: python --version
    - name: Python 3 version
      run: python3 --version
    - name: Python 2 version
      run: python2 --version
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ always() }}
