name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-16.04
    name: Debug CI
    steps:
    - name: test ls
      run: ls -l
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
